#!/usr/bin/env python3
"""Remove Unity splash screen from a WebGL build (Unity 2022.x).

Pipeline:
  WebGL.data.unityweb -> brotli -> UnityWebData -> data.unity3d (UnityFS bundle)
  -> globalgamemanagers (serialized assets) -> patch fields via UnityPy

For .unityweb (Decompression Fallback) builds the patched data is written
back as an uncompressed WebGL.data and index.html is repointed at it, since
Unity's brotli marker cannot be regenerated by this tool.

Patched fields:
  BuildSettings.hasPROVersion        = True
  BuildSettings.isNoWatermarkBuild   = True
  BuildSettings.isTrial              = False
  PlayerSettings.m_ShowUnitySplashScreen = False
  PlayerSettings.m_ShowUnitySplashLogo   = False

Usage:
  python3 remove_splash.py --diag Build/WebGL
  python3 remove_splash.py Build/WebGL
"""

import argparse
import gzip
import os
import shutil
import struct
import sys

import brotli
import UnityPy


def find_data_file(build_dir):
    build_dir = os.path.join(build_dir, "Build")
    if not os.path.isdir(build_dir):
        build_dir = build_dir if os.path.isdir(build_dir) else None
    if not build_dir:
        return None
    for name in sorted(os.listdir(build_dir)):
        if name.endswith((".data", ".data.br", ".data.gz", ".data.unityweb")):
            return os.path.join(build_dir, name)
    return None


def decompress(path):
    if path.endswith(".br"):
        with open(path, "rb") as f:
            return brotli.decompress(f.read())
    if path.endswith(".gz"):
        with open(path, "rb") as f:
            return gzip.decompress(f.read())
    if path.endswith(".unityweb"):
        # UnityWeb Compressed Content: the whole file is a brotli stream
        # (the "UnityWeb Compressed Content (brotli)" marker is a brotli
        # metadata block embedded by Unity's compressor).
        with open(path, "rb") as f:
            return brotli.decompress(f.read())
    with open(path, "rb") as f:
        return f.read()


def update_index_html(build_dir, old_name, new_name):
    idx = os.path.join(build_dir, "index.html")
    if not os.path.isfile(idx):
        return
    with open(idx, "r") as f:
        content = f.read()
    if old_name not in content:
        return
    with open(idx, "w") as f:
        f.write(content.replace(old_name, new_name))
    print("index.html: %s -> %s" % (old_name, new_name))


def compress(path, data):
    if path.endswith(".br"):
        with open(path, "wb") as f:
            f.write(brotli.compress(data, quality=11))
    elif path.endswith(".gz"):
        with open(path, "wb") as f:
            f.write(gzip.compress(data))
    else:
        with open(path, "wb") as f:
            f.write(data)


MAGIC_UNITYWEB = b"UnityWebData1.0\x00"


def parse_unityweb(data):
    assert data[: len(MAGIC_UNITYWEB)] == MAGIC_UNITYWEB, "not a UnityWebData file"
    first_file_offset = struct.unpack_from("<I", data, len(MAGIC_UNITYWEB))[0]
    pos = len(MAGIC_UNITYWEB) + 4
    files = []
    while pos < first_file_offset:
        file_offset, file_size, name_size = struct.unpack_from("<III", data, pos)
        pos += 12
        name = data[pos : pos + name_size].decode("utf-8", errors="replace")
        pos += name_size
        files.append((name, file_offset, file_size))
    assert pos == first_file_offset, "unexpected UnityWebData layout"
    return files


def repack_unityweb(entries):
    table_len = 0
    for name, content in entries:
        table_len += 12 + len(name.encode("utf-8"))
    first_file_offset = len(MAGIC_UNITYWEB) + 4 + table_len
    out = bytearray()
    out += MAGIC_UNITYWEB
    out += struct.pack("<I", first_file_offset)
    off = first_file_offset
    for name, content in entries:
        name_bytes = name.encode("utf-8")
        out += struct.pack("<III", off, len(content), len(name_bytes))
        out += name_bytes
        off += len(content)
    for name, content in entries:
        out += content
    return bytes(out)


def load_bundle(data_unity3d_bytes):
    env = UnityPy.load(data_unity3d_bytes)
    return env


def patch_asset(tree, changes):
    applied = []
    for field, new in changes.items():
        if field not in tree:
            continue
        old = tree[field]
        if old == new:
            applied.append((field, old, new, "unchanged"))
        else:
            applied.append((field, old, new, "patched"))
            tree[field] = new
    return tree, applied


def run(env, changes, diag_only):
    results = []
    for obj in env.objects:
        tree_name = obj.type.name if obj.type is not None else str(obj.type_id)
        if tree_name not in changes:
            continue
        if obj.typetree is None:
            tree = obj.read_typetree()
        else:
            tree = obj.typetree
        print("== %s (path_id=%s) ==" % (tree_name, obj.path_id))
        for field in sorted(changes[tree_name]):
            print("  %-30s -> %s" % (field, tree.get(field)))
        if not diag_only:
            new_tree, applied = patch_asset(tree, changes[tree_name])
            obj.save_typetree(new_tree)
            for field, old, new, status in applied:
                print("  [%s] %s: %s -> %s" % (status, field, old, new))
        results.append((tree_name, obj))
    return results


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("build_dir")
    ap.add_argument("--diag", action="store_true")
    args = ap.parse_args()

    data_path = find_data_file(args.build_dir)
    if not data_path:
        sys.exit("no WebGL data file found under %s" % args.build_dir)
    print("data file: %s" % data_path)

    raw = decompress(data_path)
    print("decompressed: %d bytes" % len(raw))

    files = parse_unityweb(raw)
    print("UnityWebData entries:")
    for name, off, size in files:
        print("  %-40s off=0x%x size=%d" % (name, off, size))

    bundle_name = next(
        (name for name, _, _ in files if name.endswith("data.unity3d")), None
    )
    if bundle_name is None:
        sys.exit("no data.unity3d found in UnityWebData")

    bundle_off, bundle_size = next(
        (off, size) for name, off, size in files if name == bundle_name
    )
    bundle_bytes = raw[bundle_off : bundle_off + bundle_size]

    changes = {
        "PlayerSettings": {
            "m_ShowUnitySplashScreen": False,
            "m_ShowUnitySplashLogo": False,
        },
        "BuildSettings": {
            "hasPROVersion": True,
            "isNoWatermarkBuild": True,
            "isTrial": False,
        },
    }

    env = load_bundle(bundle_bytes)
    run(env, changes, args.diag)

    if args.diag:
        return

    tmp_dir = os.path.join(os.path.dirname(data_path), ".patched_bundle.tmp")
    os.makedirs(tmp_dir, exist_ok=True)
    env.save(pack="lz4", out_path=tmp_dir)
    saved = [f for f in os.listdir(tmp_dir) if not f.startswith(".")]
    if not saved:
        sys.exit("bundle save produced no files")
    with open(os.path.join(tmp_dir, saved[0]), "rb") as f:
        new_bundle_bytes = f.read()
    shutil.rmtree(tmp_dir)
    print("new bundle size: %d (was %d)" % (len(new_bundle_bytes), len(bundle_bytes)))

    if os.path.exists(data_path):
        backup = data_path + ".bak"
        if not os.path.exists(backup):
            with open(data_path, "rb") as f, open(backup, "wb") as g:
                g.write(f.read())
            print("backup written: %s" % backup)

    entries = [
        (name, new_bundle_bytes if name == bundle_name else raw[off : off + size])
        for name, off, size in files
    ]
    new_raw = repack_unityweb(entries)

    if data_path.endswith(".unityweb"):
        # Recompressing back to .unityweb would lose Unity's brotli marker,
        # so emit an uncompressed .data file and repoint index.html at it.
        out_path = data_path[: -len(".unityweb")]
        with open(out_path, "wb") as f:
            f.write(new_raw)
        print("patched and written (uncompressed): %s" % out_path)
        build_dir = os.path.dirname(os.path.dirname(data_path))
        update_index_html(
            build_dir, os.path.basename(data_path), os.path.basename(out_path)
        )
    else:
        compress(data_path, new_raw)
        print("patched and written: %s" % data_path)


if __name__ == "__main__":
    main()
